from __future__ import annotations

import shutil
import uuid
from pathlib import Path

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import FileResponse
from pydantic import BaseModel

from .pipeline import run_pipeline

app = FastAPI(
    title="EAMA API",
    description=(
        "Upload a CSV or Excel file and get back anomaly detection "
        "results, consolidated business alerts, and downloadable "
        "Excel/PDF reports."
    ),
)

UPLOAD_DIR = Path("data/api_uploads")
OUTPUT_DIR = Path("data/api_outputs")
STATIC_DIR = Path("static")
ALLOWED_EXTENSIONS = {".csv", ".xlsx", ".xls"}


@app.get("/")
async def frontend() -> FileResponse:
    """Serve the EAMA web interface."""
    index_path = STATIC_DIR / "index.html"
    if not index_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Frontend not found. Expected static/index.html.",
        )
    return FileResponse(index_path, media_type="text/html")


class AnalyzeResponse(BaseModel):
    job_id: str
    records_loaded: int
    anomalies_detected: int
    business_alerts_total: int
    business_alerts_new: int
    email_drafts_created: int
    new_alert_summaries: list[str]
    all_alert_summaries: list[str]

    used_auto_config: bool
    auto_detected_date_column: str | None
    auto_detected_metrics: list[str]
    auto_detected_dimensions: list[str]
    auto_config_warnings: list[str]

    excel_report_url: str
    pdf_report_url: str
    findings_csv_url: str
    business_alerts_csv_url: str


@app.post("/api/analyze", response_model=AnalyzeResponse)
async def analyze(file: UploadFile = File(...)) -> AnalyzeResponse:
    """Upload a CSV/XLSX/XLS file and run the full EAMA pipeline on it.

    No config is required -- EAMA inspects the file and generates one
    automatically, the same way `eama.cli` behaves without --config.
    """
    original_suffix = Path(file.filename or "").suffix.lower()

    if original_suffix not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Unsupported file type '{original_suffix}'. "
                f"EAMA accepts .csv, .xlsx, and .xls files."
            ),
        )

    job_id = uuid.uuid4().hex[:12]

    job_upload_dir = UPLOAD_DIR / job_id
    job_output_dir = OUTPUT_DIR / job_id
    job_upload_dir.mkdir(parents=True, exist_ok=True)
    job_output_dir.mkdir(parents=True, exist_ok=True)

    saved_input_path = job_upload_dir / f"input{original_suffix}"

    with saved_input_path.open("wb") as destination:
        shutil.copyfileobj(file.file, destination)

    try:
        result = run_pipeline(
            input_path=saved_input_path,
            config_path=None,
            output_path=job_output_dir / "anomalies.csv",
        )
    except ValueError as error:
        raise HTTPException(status_code=422, detail=str(error)) from error

    return AnalyzeResponse(
        job_id=job_id,
        records_loaded=result.records_loaded,
        anomalies_detected=result.anomalies_detected,
        business_alerts_total=result.business_alerts_total,
        business_alerts_new=result.business_alerts_new,
        email_drafts_created=result.email_drafts_created,
        new_alert_summaries=result.new_alert_summaries,
        all_alert_summaries=result.all_alert_summaries,
        used_auto_config=result.used_auto_config,
        auto_detected_date_column=result.auto_detected_date_column,
        auto_detected_metrics=result.auto_detected_metrics,
        auto_detected_dimensions=result.auto_detected_dimensions,
        auto_config_warnings=result.auto_config_warnings,
        excel_report_url=f"/api/download/{job_id}/excel",
        pdf_report_url=f"/api/download/{job_id}/pdf",
        findings_csv_url=f"/api/download/{job_id}/findings",
        business_alerts_csv_url=f"/api/download/{job_id}/alerts",
    )


_DOWNLOAD_FILES = {
    "excel": ("EAMA_Weekly_Alert_Report.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    "pdf": ("EAMA_Weekly_Alert_Report.pdf", "application/pdf"),
    "findings": ("anomalies.csv", "text/csv"),
    "alerts": ("business_alerts.csv", "text/csv"),
}


@app.get("/api/download/{job_id}/{report_type}")
async def download(job_id: str, report_type: str) -> FileResponse:
    """Download a report generated by a previous /api/analyze call."""
    if report_type not in _DOWNLOAD_FILES:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Unknown report type '{report_type}'. "
                f"Valid options: {', '.join(_DOWNLOAD_FILES)}."
            ),
        )

    filename, media_type = _DOWNLOAD_FILES[report_type]

    # job_id comes from a URL path segment; keep it to safe characters
    # only so it can't be used to escape OUTPUT_DIR (e.g. "../../etc").
    if not job_id.isalnum():
        raise HTTPException(status_code=400, detail="Invalid job_id.")

    file_path = OUTPUT_DIR / job_id / filename

    if not file_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Report not found. It may not have been generated for this job.",
        )

    return FileResponse(file_path, media_type=media_type, filename=filename)


@app.get("/api/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}